[project]
name = "hackathon-todo-phase1"
version = "1.0.0"
description = "Phase I: Console Todo Application - Hackathon II Evolution of Todo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
todo = "src.main:main"
